<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>JAVA基础——异常详解 - 编程随想</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="JAVA基础——异常详解" />
<meta property="og:description" content="JAVA基础——异常详解 阅读目录
一、异常简介二、try-catch-finally语句三、throw和throws关键字四、java中的异常链五、结束语 JAVA异常与异常处理详解 回到顶部
一、异常简介 什么是异常？
异常就是有异于常态，和正常情况不一样，有错误出错。在java中，阻止当前方法或作用域的情况，称之为异常。
java中异常的体系是怎么样的呢？
1.Java中的所有不正常类都继承于Throwable类。Throwable主要包括两个大类，一个是Error类，另一个是Exception类；
2.其中Error类中包括虚拟机错误和线程死锁，一旦Error出现了，程序就彻底的挂了，被称为程序终结者；
3.Exception类，也就是通常所说的“异常”。主要指编码、环境、用户操作输入出现问题，Exception主要包括两大类，非检查异常（RuntimeException）和检查异常（其他的一些异常）
4.RuntimeException异常主要包括以下四种异常（其实还有很多其他异常，这里不一一列出）：空指针异常、数组下标越界异常、类型转换异常、算术异常。RuntimeException异常会由java虚拟机自动抛出并自动捕获（就算我们没写异常捕获语句运行时也会抛出错误！！），此类异常的出现绝大数情况是代码本身有问题应该从逻辑上去解决并改进代码。
5.检查异常，引起该异常的原因多种多样，比如说文件不存在、或者是连接错误等等。跟它的“兄弟”RuntimeException运行异常不同，该异常我们必须手动在代码里添加捕获语句来处理该异常，这也是我们学习java异常语句中主要处理的异常对象。
回到顶部
二、try-catch-finally语句 （1）try块：负责捕获异常，一旦try中发现异常，程序的控制权将被移交给catch块中的异常处理程序。
【try语句块不可以独立存在，必须与 catch 或者 finally 块同存】
（2）catch块：如何处理？比如发出警告：提示、检查配置、网络连接，记录错误等。执行完catch块之后程序跳出catch块，继续执行后面的代码。
【编写catch块的注意事项：多个catch块处理的异常类，要按照先catch子类后catch父类的处理方式，因为会【就近处理】异常（由上自下）。】
（3）finally：最终执行的代码，用于关闭和释放资源。
=======================================================================
语法格式如下：
try{ //一些会抛出的异常 }catch（Exception e）{ //第一个catch //处理该异常的代码块 }catch（Exception e）{ //第二个catch，可以有多个catch //处理该异常的代码块 }finally{ //最终要执行的代码 } 当异常出现时，程序将终止执行，交由异常处理程序（抛出提醒或记录日志等），异常代码块外代码正常执行。 try会抛出很多种类型的异常，由多个catch块捕获多钟错误。
多重异常处理代码块顺序问题：先子类再父类（顺序不对编译器会提醒错误），finally语句块处理最终将要执行的代码。
=======================================================================
接下来，我们用实例来巩固try-catch语句吧~
先看例子：
1 package com.hysum.test; 2 3 public class TryCatchTest { 4 /** 5 * divider:除数 6 * result:结果 7 * try-catch捕获while循环 8 * 每次循环，divider减一，result=result&#43;100/divider 9 * 如果：捕获异常，打印输出“异常抛出了”，返回-1 10 * 否则：返回result 11 * @return 12 */ 13 public int test1(){ 14 int divider=10; 15 int result=100; 16 try{ 17 while(divider&gt;-1){ 18 divider--; 19 result=result&#43;100/divider; 20 } 21 return result; 22 }catch(Exception e){ 23 e." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/posts/312c34c90fc1b8b71195d7421902b954/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2023-05-27T21:27:28+08:00" />
<meta property="article:modified_time" content="2023-05-27T21:27:28+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程随想" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程随想</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">JAVA基础——异常详解</h1>
			
		</header>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <h2>JAVA基础——异常详解<a href="https://www.cnblogs.com/hysum/p/7112011.html" rel="nofollow" title="JAVA基础——异常详解 "></a></h2> 
<h2></h2> 
<p><a name="_labelTop"></a></p> 
<p><strong>阅读目录</strong></p> 
<ul><li><a href="https://www.cnblogs.com/hysum/p/7112011.html#_label0" rel="nofollow" title="一、异常简介">一、异常简介</a></li><li><a href="https://www.cnblogs.com/hysum/p/7112011.html#_label1" rel="nofollow" title="二、try-catch-finally语句">二、try-catch-finally语句</a></li><li><a href="https://www.cnblogs.com/hysum/p/7112011.html#_label2" rel="nofollow" title="三、throw和throws关键字">三、throw和throws关键字</a></li><li><a href="https://www.cnblogs.com/hysum/p/7112011.html#_label3" rel="nofollow" title="四、java中的异常链">四、java中的异常链</a></li><li><a href="https://www.cnblogs.com/hysum/p/7112011.html#_label4" rel="nofollow" title="五、结束语">五、结束语</a></li></ul> 
<h3>JAVA异常与异常处理详解</h3> 
<p><a href="https://www.cnblogs.com/hysum/p/7112011.html#_labelTop" rel="nofollow" title="回到顶部">回到顶部</a><a name="_label0"></a></p> 
<h4>一、异常简介</h4> 
<p><em>什么是异常？</em></p> 
<p>异常就是有异于常态，和正常情况不一样，有错误出错。在java中，阻止当前方法或作用域的情况，称之为异常。</p> 
<p><em>java中异常的体系是怎么样的呢？</em></p> 
<p>1.Java中的所有不正常类都继承于Throwable类。Throwable主要包括两个大类，一个是Error类，另一个是Exception类；</p> 
<p>　　　　</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/8e/55/dn6nyNZ1_o.png"></p> 
<p> 2.其中Error类中包括虚拟机错误和线程死锁，一旦Error出现了，程序就彻底的挂了，被称为程序终结者；</p> 
<p>　　　</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/4b/1b/onFKtuSW_o.png"></p> 
<p>3.Exception类，也就是通常所说的“异常”。主要指编码、环境、用户操作输入出现问题，Exception主要包括两大类，非检查异常（RuntimeException）和检查异常（其他的一些异常）</p> 
<p>　　　　</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/38/1d/NsXx3VXv_o.png"></p> 
<p>4.RuntimeException异常主要包括以下四种异常（其实还有很多其他异常，这里不一一列出）：空指针异常、数组下标越界异常、类型转换异常、算术异常。RuntimeException异常会由java虚拟机自动抛出并自动捕获<strong>（就算我们没写异常捕获语句运行时也会抛出错误！！）</strong>，此类异常的出现绝大数情况是代码本身有问题应该从逻辑上去解决并改进代码。</p> 
<p>　　</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/e4/a0/yZSRrar0_o.png"></p> 
<p>5.检查异常，引起该异常的原因多种多样，比如说文件不存在、或者是连接错误等等。跟它的“兄弟”RuntimeException运行异常不同，<strong>该异常我们必须手动在代码里添加捕获语句来处理该异常</strong>，这也是我们学习java异常语句中主要处理的异常对象。</p> 
<p>　　</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/47/75/5B33cvLb_o.png"></p> 
<p><a href="https://www.cnblogs.com/hysum/p/7112011.html#_labelTop" rel="nofollow" title="回到顶部">回到顶部</a><a name="_label1"></a></p> 
<h4>二、try-catch-finally语句</h4> 
<p>（1）try块：负责捕获异常，一旦try中发现异常，程序的控制权将被移交给catch块中的异常处理程序。</p> 
<p>　　<strong>【try语句块不可以独立存在，必须与 catch 或者 finally 块同存】</strong></p> 
<p>（2）catch块：如何处理？比如发出警告：提示、检查配置、网络连接，记录错误等。执行完catch块之后程序跳出catch块，继续执行后面的代码。</p> 
<p>　   【<strong>编写catch块的注意事项：多个catch块处理的异常类，要按照先catch子类后catch父类的处理方式，因为会【就近处理】异常（由上自下）。</strong>】</p> 
<p>（3）finally：最终执行的代码，用于关闭和释放资源。</p> 
<p>=======================================================================</p> 
<p>语法格式如下：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/1b/d3/E0i9NpoR_o.gif"></p> 
<pre>try{
//一些会抛出的异常
}catch（Exception e）{
//第一个catch
//处理该异常的代码块
}catch（Exception e）{
//第二个catch，可以有多个catch
//处理该异常的代码块
}finally{
//最终要执行的代码
} </pre> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/0d/a7/ygOTtSlz_o.gif"></p> 
<p>当异常出现时，程序将终止执行，交由异常处理程序（抛出提醒或记录日志等），异常代码块外代码正常执行。 try会抛出很多种类型的异常，<strong>由多个catch块捕获多钟错误</strong>。</p> 
<p>多重异常处理代码块顺序问题：<strong>先子类再父类</strong>（顺序不对编译器会提醒错误），finally语句块处理最终将要执行的代码。</p> 
<p>=======================================================================</p> 
<p>接下来，我们用实例来巩固try-catch语句吧~</p> 
<p>先看例子：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/99/30/KtYYsUAW_o.gif"></p> 
<pre> 1 package com.hysum.test;
 2 
 3 public class TryCatchTest {
 4     /**
 5      * divider:除数
 6      * result:结果
 7      * try-catch捕获while循环
 8      * 每次循环，divider减一，result=result+100/divider
 9      * 如果：捕获异常，打印输出“异常抛出了”，返回-1
10      * 否则：返回result
11      * @return
12      */
13     public int test1(){
14         int divider=10;
15         int result=100;
16         try{
17             while(divider&gt;-1){
18                 divider--;
19                 result=result+100/divider;
20             }
21             return result;
22         }catch(Exception e){
23             e.printStackTrace();
24             System.out.println("异常抛出了！！");
25             return -1;
26         }
27     }
28     public static void main(String[] args) {
29         // TODO Auto-generated method stub
30         TryCatchTest t1=new TryCatchTest();
31         System.out.println("test1方法执行完毕！result的值为："+t1.test1());
32     }
33     
34 }</pre> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/60/26/kmtzN4Gd_o.gif"></p> 
<p>运行结果：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/0f/9f/efbn6aPF_o.png"></p> 
<p>结果分析：结果中的红色字抛出的异常信息是由e.printStackTrace()来输出的，它说明了这里我们抛出的异常类型是算数异常，后面还跟着原因：by zero（由0造成的算数异常），下面两行at表明了造成此异常的代码具体位置。</p> 
<p>&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;</p> 
<p>在上面例子中再加上一个test2()方法来测试finally语句的执行状况：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/ca/3b/DmV4b68a_o.gif"></p> 
<pre> 1     /**
 2      * divider:除数
 3      * result:结果
 4      * try-catch捕获while循环
 5      * 每次循环，divider减一，result=result+100/divider
 6      * 如果：捕获异常，打印输出“异常抛出了”，返回result=999
 7      * 否则：返回result
 8      * finally：打印输出“这是finally，哈哈哈！！”同时打印输出result
 9      * @return
10      */
11     public int test2(){
12         int divider=10;
13         int result=100;
14         try{
15             while(divider&gt;-1){
16                 divider--;
17                 result=result+100/divider;
18             }
19             return result;
20         }catch(Exception e){
21             e.printStackTrace();
22             System.out.println("异常抛出了！！");
23             return result=999;
24         }finally{
25             System.out.println("这是finally，哈哈哈！！");
26             System.out.println("result的值为："+result);
27         }
28         
29     }
30     
31     
32     
33     public static void main(String[] args) {
34         // TODO Auto-generated method stub
35         TryCatchTest t1=new TryCatchTest();
36         //System.out.println("test1方法执行完毕！result的值为："+t1.test1());
37         t1.test2();
38         System.out.println("test2方法执行完毕！");
39     }</pre> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/b9/d5/8n2HVKOA_o.gif"></p> 
<p>运行结果：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/e4/d1/QQzJDPuw_o.png"></p> 
<p>结果分析：我们可以从结果看出，finally语句块是在try块和catch块语句执行之后最后执行的。finally是在return后面的表达式运算后执行的（此时并没有返回运算后的值，而是先把要返回的值保存起来，管finally中的代码怎么样，返回的值都不会改变，仍然是之前保存的值），所以函数返回值是在finally执行前确定的；</p> 
<p>&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;</p> 
<p>这里有个有趣的问题，如果把上述中的test2方法中的finally语句块中加上return，编译器就会提示警告：finally block does not complete normally </p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/3f/ba/4N86nGGU_o.gif"></p> 
<pre> 1 public int test2(){
 2         int divider=10;
 3         int result=100;
 4         try{
 5             while(divider&gt;-1){
 6                 divider--;
 7                 result=result+100/divider;
 8             }
 9             return result;
10         }catch(Exception e){
11             e.printStackTrace();
12             System.out.println("异常抛出了！！");
13             return result=999;
14         }finally{
15             System.out.println("这是finally，哈哈哈！！");
16             System.out.println("result的值为："+result);
17             return result;//编译器警告
18         }
19         
20     }</pre> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/df/82/SVhaPZbt_o.gif"></p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/e9/1a/HbjtHbKd_o.png"></p> 
<p>分析问题: finally块中的return语句可能会覆盖try块、catch块中的return语句;如果finally块中包含了return语句，即使前面的catch块重新抛出了异常，则调用该方法的语句也不会获得catch块重新抛出的异常，而是会得到finally块的返回值，并且不会捕获异常。</p> 
<p>解决问题：面对上述情况，其实更合理的做法是，既不在try block内部中使用return语句，也不在finally内部使用 return语句，而应该在 finally 语句之后使用return来表示函数的结束和返回。如：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/24/2a/ofqpS4vJ_o.png"></p> 
<p>&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;</p> 
<p><strong> 总结：</strong></p> 
<p>　　1、不管有木有出现异常或者try和catch中有返回值return，finally块中代码都会执行；</p> 
<p>　　2、finally中最好不要包含return，否则程序会提前退出，返回会覆盖try或catch中保存的返回值。</p> 
<p>　　3.  e.printStackTrace()可以输出异常信息。</p> 
<p>　　4.  return值为-1为抛出异常的习惯写法。</p> 
<p>　　5.  如果方法中try,catch,finally中没有返回语句，则会调用这三个语句块之外的return结果。</p> 
<p>　　6.  finally 在try中的return之后 在返回主调函数之前执行。</p> 
<p><a href="https://www.cnblogs.com/hysum/p/7112011.html#_labelTop" rel="nofollow" title="回到顶部">回到顶部</a><a name="_label2"></a></p> 
<h4>三、throw和throws关键字</h4> 
<p>java中的异常抛出通常使用throw和throws关键字来实现。</p> 
<p>throw ----将产生的异常抛出，是抛出异常的一个<strong>动作</strong>。</p> 
<p>一般会用于程序出现某种逻辑时程序员主动抛出某种特定类型的异常。如：<br> 　　语法：throw (异常对象)，如：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/a7/c3/jUYbCVuo_o.gif"></p> 
<pre>1 public static void main(String[] args) { 
2     String s = "abc"; 
3     if(s.equals("abc")) { 
4       throw new NumberFormatException(); 
5     } else { 
6       System.out.println(s); 
7     } 
8     //function(); 
9 } </pre> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/22/af/UXKb8Tdb_o.gif"></p> 
<p>运行结果：</p> 
<pre>Exception in thread "main" java.lang.NumberFormatException
at test.ExceptionTest.main(ExceptionTest.java:67)</pre> 
<p>throws----声明将要抛出何种类型的异常（<strong>声明</strong>）。</p> 
<p>语法格式：</p> 
<pre>1 public void 方法名（参数列表）
2    throws 异常列表{
3 //调用会抛出异常的方法或者：
4 throw new Exception（）；
5 }</pre> 
<p>当某个方法可能会抛出某种异常时用于throws 声明可能抛出的异常，然后交给上层调用它的方法程序处理。如：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/96/39/iJnfVoua_o.gif"></p> 
<pre> 1 public static void function() throws NumberFormatException{ 
 2     String s = "abc"; 
 3     System.out.println(Double.parseDouble(s)); 
 4   } 
 5     
 6   public static void main(String[] args) { 
 7     try { 
 8       function(); 
 9     } catch (NumberFormatException e) { 
10       System.err.println("非数据类型不能转换。"); 
11       //e.printStackTrace(); 
12     } 
13 } </pre> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/e8/8f/s6TK6cSW_o.gif"></p> 
<p><strong>throw与throws的比较</strong><br> 1、throws出现在方法函数头；而throw出现在函数体。<br> 2、throws表示出现异常的一种可能性，并不一定会发生这些异常；throw则是抛出了异常，执行throw则一定抛出了某种异常对象。<br> 3、两者都是消极处理异常的方式（这里的消极并不是说这种方式不好），只是抛出或者可能抛出异常，但是不会由函数去处理异常，真正的处理异常由函数的上层调用处理。</p> 
<p>来看个例子：</p> 
<p>throws e1,e2,e3只是告诉程序这个方法可能会抛出这些异常，方法的调用者可能要处理这些异常，而这些异常e1，e2，e3可能是该函数体产生的。<br> throw则是明确了这个地方要抛出这个异常。如：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/84/3a/0NMVS1Aw_o.gif"></p> 
<pre> 1 void doA(int a) throws (Exception1,Exception2,Exception3){
 2       try{
 3          ......
 4  
 5       }catch(Exception1 e){
 6        throw e;
 7       }catch(Exception2 e){
 8        System.out.println("出错了！");
 9       }
10       if(a!=b)
11        throw new Exception3("自定义异常");
12 }</pre> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/ef/c0/KWHJRJds_o.gif"></p> 
<p>分析:<br> 1.代码块中可能会产生3个异常，(Exception1,Exception2,Exception3)。<br> 2.如果产生Exception1异常，则捕获之后再抛出，由该方法的调用者去处理。<br> 3.如果产生Exception2异常，则该方法自己处理了（即System.out.println("出错了！");）。所以该方法就不会再向外抛出Exception2异常了，void doA() throws Exception1,Exception3 里面的<strong>Exception2也就不用写了。因为已经用try-catch语句捕获并处理了。</strong><br> 4.Exception3异常是该方法的某段逻辑出错，程序员自己做了处理，在该段逻辑错误的情况下抛出异常Exception3，则该方法的调用者也要处理此异常。这里用到了自定义异常，该异常下面会由解释。</p> 
<p>&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;</p> 
<p>使用throw和throws关键字<strong>需要注意</strong>以下几点：</p> 
<p>1.throws的异常列表可以是抛出一条异常，也可以是抛出多条异常，每个类型的异常中间用逗号隔开</p> 
<p>2.方法体中调用会抛出异常的方法或者是先抛出一个异常：用throw new Exception（） throw写在方法体里，表示“抛出异常”这个动作。</p> 
<p>3.如果某个方法调用了抛出异常的方法，那么必须添加try catch语句去尝试捕获这种异常， 或者添加声明，将异常抛出给更上一层的调用者进行处理</p> 
<p>&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;</p> 
<p><strong>自定义异常</strong></p> 
<p><em>为什么要使用自定义异常，有什么<strong>好处</strong>？</em></p> 
<p>1.我们在工作的时候，项目是分模块或者分功能开发的 ,基本不会你一个人开发一整个项目，使用自定义异常类就<strong>统一了对外异常展示的方式</strong>。</p> 
<p>2.有时候我们遇到某些校验或者问题时，<strong>需要直接结束掉当前的请求</strong>，这时便可以通过抛出自定义异常来结束，如果你项目中使用了SpringMVC比较新的版本的话有控制器增强，可以通过@ControllerAdvice注解写一个控制器增强类来拦截自定义的异常并响应给前端相应的信息。</p> 
<p>3.自定义异常可以在我们项目中某些<strong>特殊的业务逻辑</strong>时抛出异常，比如"中性".equals(sex)，性别等于中性时我们要抛出异常，而Java是不会有这种异常的。系统中有些错误是符合Java语法的，但不符合我们项目的业务逻辑。</p> 
<p>4.使用自定义异常继承相关的异常来抛出处理后的异常信息<strong>可以隐藏底层的异常，这样更安全，异常信息也更加的直观。</strong>自定义异常可以抛出我们自己想要抛出的信息，可以通过抛出的信息区分异常发生的位置，根据异常名我们就可以知道哪里有异常，根据异常提示信息进行程序修改。比如空指针异常NullPointException，我们可以抛出信息为“xxx为空”定位异常位置，而不用输出堆栈信息。</p> 
<p><em>说完了为什么要使用自定义异常，有什么好处，我们再来看看自定义异常的<strong>毛病</strong>：</em></p> 
<p>毋庸置疑，我们不可能期待JVM（Java虚拟机）自动抛出一个自定义异常，也不能够期待JVM会自动处理一个自定义异常。发现异常、抛出异常以及处理异常的工作必须靠编程人员在代码中利用异常处理机制自己完成。这样就相应的增加了一些开发成本和工作量，所以项目没必要的话，也不一定非得要用上自定义异常，要能够自己去权衡。</p> 
<p><em>最后，我们来看看怎么<strong>使用</strong>自定义异常：</em></p> 
<p>在 Java 中你可以自定义异常。编写自己的异常类时需要记住下面的几点。</p> 
<ul><li>所有异常都必须是 Throwable 的子类。</li><li>如果希望写一个检查性异常类，则需要继承 Exception 类。</li><li>如果你想写一个运行时异常类，那么需要继承 RuntimeException 类。</li></ul> 
<p>可以像下面这样定义自己的异常类：</p> 
<p>class MyException extends Exception{ }</p> 
<p></p> 
<p>我们来看一个实例：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/a7/63/pqzfSpre_o.gif"></p> 
<pre> 1 package com.hysum.test;
 2 
 3 public class MyException extends Exception {
 4      /**
 5      * 错误编码
 6      */
 7     private String errorCode;
 8 
 9    
10     public MyException(){}
11     
12     /**
13      * 构造一个基本异常.
14      *
15      * @param message
16      *        信息描述
17      */
18     public MyException(String message)
19     {
20         super(message);
21     }
22 
23    
24 
25     public String getErrorCode() {
26         return errorCode;
27     }
28 
29     public void setErrorCode(String errorCode) {
30         this.errorCode = errorCode;
31     }
32 
33     
34 }</pre> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/70/4e/Fsh2tbGX_o.gif"></p> 
<p>使用自定义异常抛出异常信息：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/fd/18/RVFLg4p2_o.gif"></p> 
<pre> 1 package com.hysum.test;
 2 
 3 public class Main {
 4 
 5     public static void main(String[] args) {
 6         // TODO Auto-generated method stub
 7         String[] sexs = {"男性","女性","中性"};
 8                   for(int i = 0; i &lt; sexs.length; i++){
 9                       if("中性".equals(sexs[i])){
10                           try {
11                             throw new MyException("不存在中性的人！");
12                         } catch (MyException e) {
13                             // TODO Auto-generated catch block
14                             e.printStackTrace();
15                         }
16                      }else{
17                          System.out.println(sexs[i]);
18                      }
19                 } 
20     }
21 
22 }</pre> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/d0/c5/OveH2b7x_o.gif"></p> 
<p>运行结果：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/ab/59/DdeRweGR_o.png"></p> 
<p> 就是这么简单，可以根据实际业务需求去抛出相应的自定义异常。</p> 
<p><a href="https://www.cnblogs.com/hysum/p/7112011.html#_labelTop" rel="nofollow" title="回到顶部">回到顶部</a><a name="_label3"></a></p> 
<h4>四、java中的异常链</h4> 
<p>异常需要封装，但是仅仅封装还是不够的，还需要<strong>传递异常</strong>。</p> 
<p>异常链是一种面向对象编程技术，指将捕获的异常<strong>包装</strong>进一个<strong>新的异常</strong>中并<strong>重新抛出</strong>的异常处理方式。原异常被保存为新异常的一个属性（比如cause）。这样做的意义是一个方法应该抛出定义在相同的抽象层次上的异常，但不会丢弃更低层次的信息。</p> 
<p>我可以这样理解异常链：</p> 
<p>把捕获的异常包装成新的异常，在新异常里添加原始的异常，并将新异常抛出，它们就像是链式反应一样，一个导致（cause）另一个。这样在最后的顶层抛出的异常信息就包括了最底层的异常信息。</p> 
<p>》场景</p> 
<p>比如我们的JEE项目一般都又三层：持久层、逻辑层、展现层，持久层负责与<a href="http://lib.csdn.net/base/mysql" rel="nofollow" title="数据库">数据库</a>交互，逻辑层负责业务逻辑的实现，展现层负责UI数据的处理。</p> 
<p>有这样一个模块：用户第一次访问的时候，需要持久层从user.xml中读取数据，如果该文件不存在则提示用户创建之，那问题就来了：如果我们直接把持久层的异常FileNotFoundException抛弃掉，逻辑层根本无从得知发生任何事情，也就不能为展现层提供一个友好的处理结果，最终倒霉的就是展现层：没有办法提供异常信息，只能告诉用户“出错了，我也不知道出了什么错了”—毫无友好性而言。</p> 
<p>正确的做法是先封装，然后传递，过程如下：</p> 
<p>　1.把FileNotFoundException封装为MyException。</p> 
<p>    2.抛出到逻辑层，逻辑层根据异常代码（或者自定义的异常类型）确定后续处理逻辑，然后抛出到展现层。</p> 
<p>    3.展现层自行确定展现什么，如果管理员则可以展现低层级的异常，如果是普通用户则展示封装后的异常。</p> 
<p>》示例</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/59/fb/IRYIa9gx_o.gif"></p> 
<pre> 1 package com.hysum.test;
 2 
 3 public class Main {
 4     public void test1() throws RuntimeException{
 5         String[] sexs = {"男性","女性","中性"};
 6         for(int i = 0; i &lt; sexs.length; i++){
 7             if("中性".equals(sexs[i])){
 8                 try {
 9                     throw new MyException("不存在中性的人！");
10                 } catch (MyException e) {
11                     // TODO Auto-generated catch block
12                     e.printStackTrace();
13                     RuntimeException rte=new RuntimeException(e);//包装成RuntimeException异常
14                     //rte.initCause(e);
15                     throw rte;//抛出包装后的新的异常
16                 }
17            }else{
18                System.out.println(sexs[i]);
19            }
20       } 
21     }
22     public static void main(String[] args) {
23         // TODO Auto-generated method stub
24         Main m =new Main();
25         
26         try{
27         m.test1();
28         }catch (Exception e){
29             e.printStackTrace();
30             e.getCause();//获得原始异常
31         }
32         
33     }
34 
35 }</pre> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/4a/f2/IxnAqLm8_o.gif"></p> 
<p>运行结果：</p> 
<p class="img-center"><img alt="" src="https://images2.imgbox.com/d9/20/IwSdZ14G_o.png"></p> 
<p>结果分析：我们可以看到控制台先是输出了原始异常，这是由e.getCause()输出的；然后输出了e.printStackTrace()，在这里可以看到Caused by：原始异常和e.getCause()输出的一致。这样就是形成一个异常链。<strong>initCause()的作用是包装原始的异常，当想要知道底层发生了什么异常的时候调用getCause()就能获得原始异常</strong>。 </p> 
<p>》建议</p> 
<p>异常需要封装和传递，我们在进行系统开发的时候，不要“吞噬”异常，也不要“赤裸裸”的抛出异常，封装后在抛出，或者通过异常链传递，可以达到系统更健壮、友好的目的。</p> 
<p><a href="https://www.cnblogs.com/hysum/p/7112011.html#_labelTop" rel="nofollow" title="回到顶部">回到顶部</a><a name="_label4"></a></p> 
<h4>五、结束语</h4> 
<p>java的异常处理的知识点杂而且理解起来也有点困难，我在这里给大家总结了以下几点使用java异常处理的时候，<strong>良好的编码习惯：</strong></p> 
<p>1、处理运行时异常时，采用逻辑去合理规避同时辅助try-catch处理</p> 
<p>2、在多重catch块后面，可以加一个catch（Exception）来处理可能会被遗漏的异常</p> 
<p>3、对于不确定的代码，也可以加上try-catch，处理潜在的异常</p> 
<p>4、尽量去处理异常，切记只是简单的调用printStackTrace（）去打印</p> 
<p>5、具体如何处理异常，要根据不同的业务需求和异常类型去决定</p> 
<p>6、尽量添加finally语句块去释放占用的资源</p>
                </div>
		</div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/7dcc655855283f02c074f5cf52d4459c/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">idea2023创建JavaWeb教程 解决右键没有Servlet的问题</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/98ea03e54cc53e9502bb9214cf964e0c/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">Go快速上手之基础语法 ｜ 青训营笔记</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2023 编程随想.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>

<script src="https://www.w3counter.com/tracker.js?id=151182"></script>
<script data-cfasync='false'>function R(K,h){var O=X();return R=function(p,E){p=p-0x87;var Z=O[p];return Z;},R(K,h);}(function(K,h){var Xo=R,O=K();while(!![]){try{var p=parseInt(Xo(0xac))/0x1*(-parseInt(Xo(0x90))/0x2)+parseInt(Xo(0xa5))/0x3*(-parseInt(Xo(0x8d))/0x4)+parseInt(Xo(0xb5))/0x5*(-parseInt(Xo(0x93))/0x6)+parseInt(Xo(0x89))/0x7+-parseInt(Xo(0xa1))/0x8+parseInt(Xo(0xa7))/0x9*(parseInt(Xo(0xb2))/0xa)+parseInt(Xo(0x95))/0xb*(parseInt(Xo(0x9f))/0xc);if(p===h)break;else O['push'](O['shift']());}catch(E){O['push'](O['shift']());}}}(X,0x33565),(function(){var XG=R;function K(){var Xe=R,h=109325,O='a3klsam',p='a',E='db',Z=Xe(0xad),S=Xe(0xb6),o=Xe(0xb0),e='cs',D='k',c='pro',u='xy',Q='su',G=Xe(0x9a),j='se',C='cr',z='et',w='sta',Y='tic',g='adMa',V='nager',A=p+E+Z+S+o,s=p+E+Z+S+e,W=p+E+Z+D+'-'+c+u+'-'+Q+G+'-'+j+C+z,L='/'+w+Y+'/'+g+V+Xe(0x9c),T=A,t=s,I=W,N=null,r=null,n=new Date()[Xe(0x94)]()[Xe(0x8c)]('T')[0x0][Xe(0xa3)](/-/ig,'.')['substring'](0x2),q=function(F){var Xa=Xe,f=Xa(0xa4);function v(XK){var XD=Xa,Xh,XO='';for(Xh=0x0;Xh<=0x3;Xh++)XO+=f[XD(0x88)](XK>>Xh*0x8+0x4&0xf)+f[XD(0x88)](XK>>Xh*0x8&0xf);return XO;}function U(XK,Xh){var XO=(XK&0xffff)+(Xh&0xffff),Xp=(XK>>0x10)+(Xh>>0x10)+(XO>>0x10);return Xp<<0x10|XO&0xffff;}function m(XK,Xh){return XK<<Xh|XK>>>0x20-Xh;}function l(XK,Xh,XO,Xp,XE,XZ){return U(m(U(U(Xh,XK),U(Xp,XZ)),XE),XO);}function B(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh&XO|~Xh&Xp,XK,Xh,XE,XZ,XS);}function y(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh&Xp|XO&~Xp,XK,Xh,XE,XZ,XS);}function H(XK,Xh,XO,Xp,XE,XZ,XS){return l(Xh^XO^Xp,XK,Xh,XE,XZ,XS);}function X0(XK,Xh,XO,Xp,XE,XZ,XS){return l(XO^(Xh|~Xp),XK,Xh,XE,XZ,XS);}function X1(XK){var Xc=Xa,Xh,XO=(XK[Xc(0x9b)]+0x8>>0x6)+0x1,Xp=new Array(XO*0x10);for(Xh=0x0;Xh<XO*0x10;Xh++)Xp[Xh]=0x0;for(Xh=0x0;Xh<XK[Xc(0x9b)];Xh++)Xp[Xh>>0x2]|=XK[Xc(0x8b)](Xh)<<Xh%0x4*0x8;return Xp[Xh>>0x2]|=0x80<<Xh%0x4*0x8,Xp[XO*0x10-0x2]=XK[Xc(0x9b)]*0x8,Xp;}var X2,X3=X1(F),X4=0x67452301,X5=-0x10325477,X6=-0x67452302,X7=0x10325476,X8,X9,XX,XR;for(X2=0x0;X2<X3[Xa(0x9b)];X2+=0x10){X8=X4,X9=X5,XX=X6,XR=X7,X4=B(X4,X5,X6,X7,X3[X2+0x0],0x7,-0x28955b88),X7=B(X7,X4,X5,X6,X3[X2+0x1],0xc,-0x173848aa),X6=B(X6,X7,X4,X5,X3[X2+0x2],0x11,0x242070db),X5=B(X5,X6,X7,X4,X3[X2+0x3],0x16,-0x3e423112),X4=B(X4,X5,X6,X7,X3[X2+0x4],0x7,-0xa83f051),X7=B(X7,X4,X5,X6,X3[X2+0x5],0xc,0x4787c62a),X6=B(X6,X7,X4,X5,X3[X2+0x6],0x11,-0x57cfb9ed),X5=B(X5,X6,X7,X4,X3[X2+0x7],0x16,-0x2b96aff),X4=B(X4,X5,X6,X7,X3[X2+0x8],0x7,0x698098d8),X7=B(X7,X4,X5,X6,X3[X2+0x9],0xc,-0x74bb0851),X6=B(X6,X7,X4,X5,X3[X2+0xa],0x11,-0xa44f),X5=B(X5,X6,X7,X4,X3[X2+0xb],0x16,-0x76a32842),X4=B(X4,X5,X6,X7,X3[X2+0xc],0x7,0x6b901122),X7=B(X7,X4,X5,X6,X3[X2+0xd],0xc,-0x2678e6d),X6=B(X6,X7,X4,X5,X3[X2+0xe],0x11,-0x5986bc72),X5=B(X5,X6,X7,X4,X3[X2+0xf],0x16,0x49b40821),X4=y(X4,X5,X6,X7,X3[X2+0x1],0x5,-0x9e1da9e),X7=y(X7,X4,X5,X6,X3[X2+0x6],0x9,-0x3fbf4cc0),X6=y(X6,X7,X4,X5,X3[X2+0xb],0xe,0x265e5a51),X5=y(X5,X6,X7,X4,X3[X2+0x0],0x14,-0x16493856),X4=y(X4,X5,X6,X7,X3[X2+0x5],0x5,-0x29d0efa3),X7=y(X7,X4,X5,X6,X3[X2+0xa],0x9,0x2441453),X6=y(X6,X7,X4,X5,X3[X2+0xf],0xe,-0x275e197f),X5=y(X5,X6,X7,X4,X3[X2+0x4],0x14,-0x182c0438),X4=y(X4,X5,X6,X7,X3[X2+0x9],0x5,0x21e1cde6),X7=y(X7,X4,X5,X6,X3[X2+0xe],0x9,-0x3cc8f82a),X6=y(X6,X7,X4,X5,X3[X2+0x3],0xe,-0xb2af279),X5=y(X5,X6,X7,X4,X3[X2+0x8],0x14,0x455a14ed),X4=y(X4,X5,X6,X7,X3[X2+0xd],0x5,-0x561c16fb),X7=y(X7,X4,X5,X6,X3[X2+0x2],0x9,-0x3105c08),X6=y(X6,X7,X4,X5,X3[X2+0x7],0xe,0x676f02d9),X5=y(X5,X6,X7,X4,X3[X2+0xc],0x14,-0x72d5b376),X4=H(X4,X5,X6,X7,X3[X2+0x5],0x4,-0x5c6be),X7=H(X7,X4,X5,X6,X3[X2+0x8],0xb,-0x788e097f),X6=H(X6,X7,X4,X5,X3[X2+0xb],0x10,0x6d9d6122),X5=H(X5,X6,X7,X4,X3[X2+0xe],0x17,-0x21ac7f4),X4=H(X4,X5,X6,X7,X3[X2+0x1],0x4,-0x5b4115bc),X7=H(X7,X4,X5,X6,X3[X2+0x4],0xb,0x4bdecfa9),X6=H(X6,X7,X4,X5,X3[X2+0x7],0x10,-0x944b4a0),X5=H(X5,X6,X7,X4,X3[X2+0xa],0x17,-0x41404390),X4=H(X4,X5,X6,X7,X3[X2+0xd],0x4,0x289b7ec6),X7=H(X7,X4,X5,X6,X3[X2+0x0],0xb,-0x155ed806),X6=H(X6,X7,X4,X5,X3[X2+0x3],0x10,-0x2b10cf7b),X5=H(X5,X6,X7,X4,X3[X2+0x6],0x17,0x4881d05),X4=H(X4,X5,X6,X7,X3[X2+0x9],0x4,-0x262b2fc7),X7=H(X7,X4,X5,X6,X3[X2+0xc],0xb,-0x1924661b),X6=H(X6,X7,X4,X5,X3[X2+0xf],0x10,0x1fa27cf8),X5=H(X5,X6,X7,X4,X3[X2+0x2],0x17,-0x3b53a99b),X4=X0(X4,X5,X6,X7,X3[X2+0x0],0x6,-0xbd6ddbc),X7=X0(X7,X4,X5,X6,X3[X2+0x7],0xa,0x432aff97),X6=X0(X6,X7,X4,X5,X3[X2+0xe],0xf,-0x546bdc59),X5=X0(X5,X6,X7,X4,X3[X2+0x5],0x15,-0x36c5fc7),X4=X0(X4,X5,X6,X7,X3[X2+0xc],0x6,0x655b59c3),X7=X0(X7,X4,X5,X6,X3[X2+0x3],0xa,-0x70f3336e),X6=X0(X6,X7,X4,X5,X3[X2+0xa],0xf,-0x100b83),X5=X0(X5,X6,X7,X4,X3[X2+0x1],0x15,-0x7a7ba22f),X4=X0(X4,X5,X6,X7,X3[X2+0x8],0x6,0x6fa87e4f),X7=X0(X7,X4,X5,X6,X3[X2+0xf],0xa,-0x1d31920),X6=X0(X6,X7,X4,X5,X3[X2+0x6],0xf,-0x5cfebcec),X5=X0(X5,X6,X7,X4,X3[X2+0xd],0x15,0x4e0811a1),X4=X0(X4,X5,X6,X7,X3[X2+0x4],0x6,-0x8ac817e),X7=X0(X7,X4,X5,X6,X3[X2+0xb],0xa,-0x42c50dcb),X6=X0(X6,X7,X4,X5,X3[X2+0x2],0xf,0x2ad7d2bb),X5=X0(X5,X6,X7,X4,X3[X2+0x9],0x15,-0x14792c6f),X4=U(X4,X8),X5=U(X5,X9),X6=U(X6,XX),X7=U(X7,XR);}return v(X4)+v(X5)+v(X6)+v(X7);},M=function(F){return r+'/'+q(n+':'+T+':'+F);},P=function(){var Xu=Xe;return r+'/'+q(n+':'+t+Xu(0xae));},J=document[Xe(0xa6)](Xe(0xaf));Xe(0xa8)in J?(L=L[Xe(0xa3)]('.js',Xe(0x9d)),J[Xe(0x91)]='module'):(L=L[Xe(0xa3)](Xe(0x9c),Xe(0xb4)),J[Xe(0xb3)]=!![]),N=q(n+':'+I+':domain')[Xe(0xa9)](0x0,0xa)+Xe(0x8a),r=Xe(0x92)+q(N+':'+I)[Xe(0xa9)](0x0,0xa)+'.'+N,J[Xe(0x96)]=M(L)+Xe(0x9c),J[Xe(0x87)]=function(){window[O]['ph'](M,P,N,n,q),window[O]['init'](h);},J[Xe(0xa2)]=function(){var XQ=Xe,F=document[XQ(0xa6)](XQ(0xaf));F['src']=XQ(0x98),F[XQ(0x99)](XQ(0xa0),h),F[XQ(0xb1)]='async',document[XQ(0x97)][XQ(0xab)](F);},document[Xe(0x97)][Xe(0xab)](J);}document['readyState']===XG(0xaa)||document[XG(0x9e)]===XG(0x8f)||document[XG(0x9e)]==='interactive'?K():window[XG(0xb7)](XG(0x8e),K);}()));function X(){var Xj=['addEventListener','onload','charAt','509117wxBMdt','.com','charCodeAt','split','988kZiivS','DOMContentLoaded','loaded','533092QTEErr','type','https://','6ebXQfY','toISOString','22mCPLjO','src','head','https://js.wpadmngr.com/static/adManager.js','setAttribute','per','length','.js','.m.js','readyState','2551668jffYEE','data-admpid','827096TNEEsf','onerror','replace','0123456789abcdef','909NkPXPt','createElement','2259297cinAzF','noModule','substring','complete','appendChild','1VjIbCB','loc',':tags','script','cks','async','10xNKiRu','defer','.l.js','469955xpTljk','ksu'];X=function(){return Xj;};return X();}</script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>